name: quela
description: Senior Project / HealthCare Systems.

version: 0.5.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_graphql: ^1.0.0-rc.3
  firebase_auth: ^0.8.3
  flutter_webrtc: ^0.1.6
  flutter_bloc: ^0.9.0
  flutter_secure_storage: ^3.2.1
  fcharts: ^0.0.10
  flip_card: ^0.2.1
  meta: ^1.1.6
  equatable: ^0.2.3
  bloc: ^0.11.0
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/q-logo.png
