name: quela
description: Senior Project / HealthCare Systems.

version: 0.1.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.2.1
  flutter_graphql: ^1.0.0-rc.3
  firebase_auth: ^0.7.0
  flutter_webrtc: ^0.1.0
  meta: ^1.1.6
  flutter_secure_storage: ^3.2.0
  equatable: ^0.2.3
  bloc: ^0.8.0
  flutter_bloc: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/q-logo.png
