name: quela
description: Senior Project / HealthCare Systems.

version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.2.1
  rxdart: ^0.21.0
  flutter_graphql: ^1.0.0-rc.3
  firebase_auth: ^0.8.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/q-logo.png
